/* Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms
 * will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do
 * not exceed four million, find the sum of the even-valued terms. */
function evenFibs() {
    var lim = (4 * 10e7);
    var fibs = [1, 2];
    for (var i = fibs[fibs.length-1]; i < lim; i += fibs[i-1]) {
        fibs += i;
    }
    var evens = 0;
    function getEvens(fib) {
        if (fib[i] % 2 == 0) evens += fib[i];
    }
    return evens;
}
console.log(evenFibs());